# The resources in this file describe the system/environment under test and should not change the test being run.

non_baseline_inputs:
  $ref: '../library/environment.yaml#/non_baseline_inputs'

common:
    $ref: '../library/environment.yaml#/common'

net_rid:
    netrid_service_providers_v19:
        $content_schema: monitoring/uss_qualifier/resources/definitions/ResourceDeclaration.json
        resource_type: resources.netrid.NetRIDServiceProviders
        dependencies:
            auth_adapter: utm_auth
        specification:
            service_providers:
                - participant_id: uss2
                  injection_base_url: http://localhost:8071/ridsp/injection
                  local_debug: true
    netrid_service_providers_v22a:
        $content_schema: monitoring/uss_qualifier/resources/definitions/ResourceDeclaration.json
        resource_type: resources.netrid.NetRIDServiceProviders
        dependencies:
            auth_adapter: utm_auth
        specification:
            service_providers:
                - participant_id: uss1
                  injection_base_url: http://localhost:8081/ridsp/injection
                  local_debug: true
    netrid_observers_v19:
        $content_schema: monitoring/uss_qualifier/resources/definitions/ResourceDeclaration.json
        resource_type: resources.netrid.NetRIDObserversResource
        dependencies:
            auth_adapter: utm_auth
        specification:
            observers:
                - participant_id: uss3
                  observation_base_url: http://localhost:8073/riddp/observation
                  local_debug: true
    netrid_observers_v22a:
        $content_schema: monitoring/uss_qualifier/resources/definitions/ResourceDeclaration.json
        resource_type: resources.netrid.NetRIDObserversResource
        dependencies:
            auth_adapter: utm_auth
        specification:
            observers:
                - participant_id: uss1
                  observation_base_url: http://localhost:8083/riddp/observation
                  local_debug: true
    netrid_dss_instances_v19:
        $content_schema: monitoring/uss_qualifier/resources/definitions/ResourceDeclaration.json
        resource_type: resources.astm.f3411.DSSInstancesResource
        dependencies:
            auth_adapter: utm_auth
        specification:
            dss_instances:
                - participant_id: uss1
                  rid_version: F3411-19
                  base_url: http://localhost:8082
                  has_private_address: true
                - participant_id: uss2
                  rid_version: F3411-19
                  base_url: http://localhost:8082
                  has_private_address: true
    netrid_dss_instances_v22a:
        $content_schema: monitoring/uss_qualifier/resources/definitions/ResourceDeclaration.json
        resource_type: resources.astm.f3411.DSSInstancesResource
        dependencies:
            auth_adapter: utm_auth
        specification:
            dss_instances:
                - participant_id: uss1
                  rid_version: F3411-22a
                  base_url: http://localhost:8082/rid/v2
                  has_private_address: true
                - participant_id: uss2
                  rid_version: F3411-22a
                  base_url: http://localhost:8082/rid/v2
                  has_private_address: true
    netrid_dss_instance_v19:
        $content_schema: monitoring/uss_qualifier/resources/definitions/ResourceDeclaration.json
        resource_type: resources.astm.f3411.DSSInstanceResource
        dependencies:
            auth_adapter: utm_auth
        specification:
            participant_id: uss1
            rid_version: F3411-19
            base_url: http://localhost:8082
            has_private_address: true
    netrid_dss_instance_v22a:
        $content_schema: monitoring/uss_qualifier/resources/definitions/ResourceDeclaration.json
        resource_type: resources.astm.f3411.DSSInstanceResource
        dependencies:
            auth_adapter: utm_auth
        specification:
            participant_id: uss1
            rid_version: F3411-22a
            base_url: http://localhost:8082/rid/v2
            has_private_address: true

f3548:
    flight_planners:
        $content_schema: monitoring/uss_qualifier/resources/definitions/ResourceDeclaration.json
        resource_type: resources.flight_planning.FlightPlannersResource
        dependencies:
            auth_adapter: utm_auth
        specification:
            flight_planners:
                # uss1 is the mock_uss directly exposing scdsc functionality
                -   participant_id: uss1
                    injection_base_url: http://localhost:8074/scdsc
                    local_debug: true

                # The atproxy has been disabled since it is suspected to be responsible of issue #28. Replaced by another simple mock_uss
                # # uss2 uses atproxy, with requests being fulfilled by mock_uss with atproxy_client functionality enabled
                # -   participant_id: uss2
                #     injection_base_url: http://host.docker.internal:8075/scd

                # uss2 is the mock_uss directly exposing scdsc functionality
                -   participant_id: uss2
                    injection_base_url: http://localhost:8094/scdsc
                    local_debug: true
    scd_dss:
        $content_schema: monitoring/uss_qualifier/resources/definitions/ResourceDeclaration.json
        resource_type: resources.astm.f3548.v21.DSSInstanceResource
        dependencies:
            auth_adapter: utm_auth
        specification:
            participant_id: uss1
            base_url: http://localhost:8082
            has_private_address: true
    scd_dss_instances:
        $content_schema: monitoring/uss_qualifier/resources/definitions/ResourceDeclaration.json
        resource_type: resources.astm.f3548.v21.DSSInstancesResource
        dependencies:
            auth_adapter: utm_auth
        specification:
            dss_instances:
                - participant_id: uss1
                  base_url: http://localhost:8082
                  has_private_address: true
                - participant_id: uss2
                  base_url: http://localhost:8082
                  has_private_address: true

f3548_single_scenario:
    uss1:
        $content_schema: monitoring/uss_qualifier/resources/definitions/ResourceDeclaration.json
        resource_type: resources.flight_planning.FlightPlannerResource
        dependencies:
            auth_adapter: utm_auth
        specification:
            flight_planner:
                participant_id: uss1
                injection_base_url: http://localhost:8074/scdsc
                local_debug: true
    uss2:
        $content_schema: monitoring/uss_qualifier/resources/definitions/ResourceDeclaration.json
        resource_type: resources.flight_planning.FlightPlannerResource
        dependencies:
            auth_adapter: utm_auth
        specification:
            flight_planner:
                participant_id: uss2
                injection_base_url: http://localhost:8094/scdsc
                local_debug: true

mock_uss_instances:
    mock_uss_instances_scdsc:
        $content_schema: monitoring/uss_qualifier/resources/definitions/ResourceDeclaration.json
        resource_type: resources.interuss.mock_uss.client.MockUSSsResource
        dependencies:
            auth_adapter: utm_auth
        specification:
            instances:
                - mock_uss_base_url: http://localhost:8074
                  participant_id: uss1
                - mock_uss_base_url: http://localhost:8094
                  participant_id: uss2
