#!/usr/bin/env python3
"""
InterUSS monitoring version file generator utility.

This script generates monitoring/_version.py containing __version__ and
version variables resolved via scripts/git/get_version.py.
"""

import argparse
import os

from get_version import (
    VERSION_FILE_PATH,
    get_pep440_version,
)


def write_version_file() -> str:
    """Writes the version to a Python file defining __version__."""

    version = get_pep440_version()
    content = f'''# This file is automatically generated by scripts/git/write_version_file.py.
# Do not edit this file manually.
__version__ = "{version}"
version = __version__
'''
    os.makedirs(os.path.dirname(os.path.abspath(VERSION_FILE_PATH)), exist_ok=True)
    with open(VERSION_FILE_PATH, "w") as f:
        f.write(content)
    return version


def main() -> None:
    parser = argparse.ArgumentParser(
        description="InterUSS monitoring version file generator utility."
    )

    parser.parse_args()
    version = write_version_file()
    print(f"Wrote version {version} to {VERSION_FILE_PATH}")


if __name__ == "__main__":
    main()
