#!/usr/bin/env bash

# This script generates the content for this repository's GitHub Pages site.  It is invoked by the CI and expects the
# working folder to contain:
#   ./monitoring: this repository
#   ./artifacts/uss_qualifier/reports: Reports generated by from running uss_qualifier
#
# The content placed into ./public by this script will be published to the GitHub Pages site.

mkdir ./public
cp -r ./monitoring/github_pages/static/* ./public

mkdir -p ./public/artifacts/uss_qualifier/reports
cp -r ./artifacts/uss_qualifier/output/* ./public/artifacts/uss_qualifier/reports
