name: Minimal production probing
resources:
  second_utm_auth: resources.communications.AuthAdapterResource?
  dss_instances: resources.astm.f3548.v21.DSSInstancesResource?
  dss_datastore_cluster: resources.interuss.datastore.DatastoreDBClusterResource?
  id_generator: resources.interuss.IDGeneratorResource
  planning_area: resources.PlanningAreaResource
  test_exclusions: resources.dev.TestExclusionsResource?
  utm_client_identity: resources.communications.ClientIdentityResource
actions:
  - action_generator:
      generator_type: action_generators.astm.f3548.ForEachDSS
      resources:
        dss_instances: dss_instances
        dss_datastore_cluster: dss_datastore_cluster?
        second_utm_auth: second_utm_auth?
        id_generator: id_generator
        planning_area: planning_area
        test_exclusions: test_exclusions?
        utm_client_identity: utm_client_identity
      specification:
        dss_instances_source: dss_instances
        dss_instance_id: current_dss_instance
        action_to_repeat:
          test_suite:
            resources:
              primary_dss_instance: current_dss_instance
              second_utm_auth: second_utm_auth?
              all_dss_instances: dss_instances
              dss_datastore_cluster: dss_datastore_cluster?
              id_generator: id_generator
              planning_area: planning_area
              test_exclusions: test_exclusions?
              utm_client_identity: utm_client_identity
            on_failure: Continue
            suite_definition:
              name: Minimal production probing for primary DSS instance
              resources:
                primary_dss_instance: resources.astm.f3548.v21.DSSInstanceResource
                second_utm_auth: resources.communications.AuthAdapterResource?
                all_dss_instances: resources.astm.f3548.v21.DSSInstancesResource?
                dss_datastore_cluster: resources.interuss.datastore.DatastoreDBClusterResource?
                id_generator: resources.interuss.IDGeneratorResource
                planning_area: resources.PlanningAreaResource
                test_exclusions: resources.dev.TestExclusionsResource?
              actions:
                - test_scenario:
                    scenario_type: scenarios.astm.utm.dss.synchronization.CRSynchronization
                    resources:
                      dss: primary_dss_instance
                      other_instances: all_dss_instances
                      id_generator: id_generator
                      planning_area: planning_area
                      client_identity: utm_client_identity
                - test_scenario:
                    scenario_type: scenarios.astm.utm.dss.synchronization.USSAvailabilitySynchronization
                    resources:
                      dss: primary_dss_instance
                      other_instances: all_dss_instances
                      client_identity: utm_client_identity
                - test_scenario:
                    scenario_type: scenarios.astm.utm.dss.SubscriptionInteractionsDeletion
                    resources:
                      dss: primary_dss_instance
                      other_instances: all_dss_instances
                      id_generator: id_generator
                      planning_area: planning_area
                      utm_client_identity: utm_client_identity
                - test_scenario:
                    scenario_type: scenarios.astm.utm.dss.SubscriptionInteractions
                    resources:
                      dss: primary_dss_instance
                      other_instances: all_dss_instances
                      id_generator: id_generator
                      planning_area: planning_area
                      utm_client_identity: utm_client_identity
                - test_scenario:
                    scenario_type: scenarios.astm.utm.dss.synchronization.OIRSynchronization
                    resources:
                      dss: primary_dss_instance
                      other_instances: all_dss_instances
                      id_generator: id_generator
                      planning_area: planning_area
                      client_identity: utm_client_identity
                - test_scenario:
                    scenario_type: scenarios.astm.utm.dss.authentication.AuthenticationValidation
                    resources:
                      dss: primary_dss_instance
                      id_generator: id_generator
                      planning_area: planning_area
                - test_scenario:
                    scenario_type: scenarios.astm.utm.dss.DSSInteroperability
                    resources:
                      primary_dss_instance: primary_dss_instance
                      all_dss_instances: all_dss_instances
                      planning_area: planning_area
                      test_exclusions: test_exclusions?
                - test_scenario:
                    scenario_type: scenarios.astm.utm.dss.synchronization.SubscriptionSynchronization
                    resources:
                      dss: primary_dss_instance
                      other_instances: all_dss_instances
                      id_generator: id_generator
                      planning_area: planning_area
                      second_utm_auth: second_utm_auth
                - test_scenario:
                    scenario_type: scenarios.astm.utm.dss.DatastoreAccess
                    resources:
                      datastore_cluster: dss_datastore_cluster
                - test_scenario:
                    scenario_type: scenarios.astm.utm.dss.Report
                    resources:
                      dss: primary_dss_instance
      on_failure: Continue
