from monitoring.mock_uss import require_config_value
from monitoring.mock_uss.config import KEY_BASE_URL, KEY_BEHAVIOR_LOCALITY


require_config_value(KEY_BASE_URL)
require_config_value(KEY_BEHAVIOR_LOCALITY)
