@startuml
center header ASTM Strategic Coordination
title Validation of operational intents

participant "DSS"
participant "Test Driver" as TD
participant "Tested USS" as T_USS

== Attempt to plan invalid flight intents ==
TD -> T_USS: PUT /inject/flight/{flightid}\n{"state": "Accepted", "volumes": //too_many_vertices//}
TD <- T_USS: 200 Ok - Planning rejected\n{"result": "Rejected"}
note left: Per ""astm.f3548.v21.OPIN0020""

TD -> T_USS: PUT /inject/flight/{flightid}\n{"state": "Accepted", "volumes": //too_far_away//}
TD <- T_USS: 200 Ok - Planning rejected\n{"result": "Rejected"}
note left: Per ""astm.f3548.v21.OPIN0030""


== Attempt to specify off-nominal volume in Accepted and Activates states ==
TD -> T_USS: PUT /inject/flight/{flightid}\n{"state": "Accepted", "off_nominal_volumes": //non_empty_volume//}
TD <- T_USS: 200 Ok - Planning rejected\n{"result": "Rejected"}
note left: Per ""astm.f3548.v21.OPIN0015""

TD -> T_USS: PUT /inject/flight/{flight1}\n{"state": "Accepted"}
TD <- T_USS: 200 Ok - Operational Intent 1 created\n{"result": "Planned"}

TD -> T_USS: PUT /inject/flight/{flight1}\n{"off_nominal_volumes": //non_empty_volume//}
TD <- T_USS: 200 Ok - Modification rejected\n{"result": "Rejected"}
note left: Per ""astm.f3548.v21.OPIN0015""

TD -> DSS: POST /dss/v1/operational_intent_references/query\nwith area_of_interest encompassing flights volumes
TD <- DSS: 200 Ok - returns Operational Intent Reference 1 managed by Tested USS
TD -> T_USS: GET /uss/v1/operational_intents/{opintent1}
TD <- T_USS: 200 Ok - returns Operational Intent 1

TD -> T_USS: PUT /inject/flight/{flight1}\n{"state": "Activated"}
TD <- T_USS: 200 Ok - Operational Intent 1 activated\n{"result": "ReadyToFly"}

TD -> T_USS: PUT /inject/flight/{flight1}\n{"off_nominal_volumes": //non_empty_volume//}
TD <- T_USS: 200 Ok - Modification rejected\n{"result": "Rejected"}
note left: Per ""astm.f3548.v21.OPIN0015""

TD -> DSS: POST /dss/v1/operational_intent_references/query\nwith area_of_interest encompassing flights volumes
TD <- DSS: 200 Ok - returns Operational Intent Reference 1 managed by Tested USS
TD -> T_USS: GET /uss/v1/operational_intents/{opintent1}
TD <- T_USS: 200 Ok - returns Operational Intent 1

@enduml
