# The resources in this file describe the system/environment under test and should not change the test being run.

non_baseline_inputs:
  non_baseline_inputs:
    - v1.test_run.resources.resource_declarations.utm_auth
    - v1.test_run.resources.resource_declarations.netrid_service_providers_v19
    - v1.test_run.resources.resource_declarations.netrid_service_providers_v22a
    - v1.test_run.resources.resource_declarations.netrid_observers_v19
    - v1.test_run.resources.resource_declarations.netrid_observers_v22a
    - v1.test_run.resources.resource_declarations.netrid_dss_instances_v19
    - v1.test_run.resources.resource_declarations.netrid_dss_instances_v22a
    - v1.test_run.resources.resource_declarations.flight_planners
    - v1.test_run.resources.resource_declarations.dss
    - v1.test_run.resources.resource_declarations.uss1
    - v1.test_run.resources.resource_declarations.uss2


common:
    utm_auth:
        $content_schema: monitoring/uss_qualifier/resources/definitions/ResourceDeclaration.json
        resource_type: resources.communications.AuthAdapterResource
        specification:
            environment_variable_containing_auth_spec: AUTH_SPEC

net_rid:
    netrid_service_providers_v19:
        $content_schema: monitoring/uss_qualifier/resources/definitions/ResourceDeclaration.json
        resource_type: resources.netrid.NetRIDServiceProviders
        dependencies:
            auth_adapter: utm_auth
        specification:
            service_providers:
                - participant_id: uss1
                  injection_base_url: http://host.docker.internal:8071/ridsp/injection
    netrid_service_providers_v22a:
        $content_schema: monitoring/uss_qualifier/resources/definitions/ResourceDeclaration.json
        resource_type: resources.netrid.NetRIDServiceProviders
        dependencies:
            auth_adapter: utm_auth
        specification:
            service_providers:
                - participant_id: uss1
                  injection_base_url: http://host.docker.internal:8081/ridsp/injection
    netrid_observers_v19:
        $content_schema: monitoring/uss_qualifier/resources/definitions/ResourceDeclaration.json
        resource_type: resources.netrid.NetRIDObserversResource
        dependencies:
            auth_adapter: utm_auth
        specification:
            observers:
                - participant_id: uss2
                  observation_base_url: http://host.docker.internal:8073/riddp/observation
    netrid_observers_v22a:
        $content_schema: monitoring/uss_qualifier/resources/definitions/ResourceDeclaration.json
        resource_type: resources.netrid.NetRIDObserversResource
        dependencies:
            auth_adapter: utm_auth
        specification:
            observers:
                - participant_id: uss2
                  observation_base_url: http://host.docker.internal:8083/riddp/observation
    netrid_dss_instances_v19:
        $content_schema: monitoring/uss_qualifier/resources/definitions/ResourceDeclaration.json
        resource_type: resources.astm.f3411.DSSInstancesResource
        dependencies:
            auth_adapter: utm_auth
        specification:
            dss_instances:
                - participant_id: uss1
                  rid_version: F3411-19
                  base_url: http://host.docker.internal:8082
                  has_private_address: true
                - participant_id: uss2
                  rid_version: F3411-19
                  base_url: http://host.docker.internal:8082
                  has_private_address: true
    netrid_dss_instances_v22a:
        $content_schema: monitoring/uss_qualifier/resources/definitions/ResourceDeclaration.json
        resource_type: resources.astm.f3411.DSSInstancesResource
        dependencies:
            auth_adapter: utm_auth
        specification:
            dss_instances:
                - participant_id: uss1
                  rid_version: F3411-22a
                  base_url: http://host.docker.internal:8082/rid/v2/
                  has_private_address: true
                - participant_id: uss2
                  rid_version: F3411-22a
                  base_url: http://host.docker.internal:8082/rid/v2/
                  has_private_address: true

f3548:
    flight_planners:
        $content_schema: monitoring/uss_qualifier/resources/definitions/ResourceDeclaration.json
        resource_type: resources.flight_planning.FlightPlannersResource
        dependencies:
            auth_adapter: utm_auth
        specification:
            flight_planners:
                # uss1 is the mock_uss directly exposing scdsc functionality
                -   participant_id: uss1
                    injection_base_url: http://host.docker.internal:8074/scdsc

                # The atproxy has been disabled since it is suspected to be responsible of issue #28. Replaced by another simple mock_uss
                # # uss2 uses atproxy, with requests being fulfilled by mock_uss with atproxy_client functionality enabled
                # -   participant_id: uss2
                #     injection_base_url: http://host.docker.internal:8075/scd

                # uss2 is the mock_uss directly exposing scdsc functionality
                -   participant_id: uss2
                    injection_base_url: http://host.docker.internal:8094/scdsc
    dss:
        $content_schema: monitoring/uss_qualifier/resources/definitions/ResourceDeclaration.json
        resource_type: resources.astm.f3548.v21.DSSInstanceResource
        dependencies:
            auth_adapter: utm_auth
        specification:
            participant_id: uss1
            base_url: http://host.docker.internal:8082
            has_private_address: true

f3548_single_scenario:
    uss1:
        $content_schema: monitoring/uss_qualifier/resources/definitions/ResourceDeclaration.json
        resource_type: resources.flight_planning.FlightPlannerResource
        dependencies:
            auth_adapter: utm_auth
        specification:
            flight_planner:
                participant_id: uss1
                injection_base_url: http://host.docker.internal:8074/scdsc
    uss2:
        $content_schema: monitoring/uss_qualifier/resources/definitions/ResourceDeclaration.json
        resource_type: resources.flight_planning.FlightPlannerResource
        dependencies:
            auth_adapter: utm_auth
        specification:
            flight_planner:
                participant_id: uss2
                injection_base_url: http://host.docker.internal:8074/scdsc
